name: publish

on:
  release:
    types: [created]

jobs:
  build:
    name: publish package to hex
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: jdx/mise-action@v2
    - name: publish package to hex
      run: make publish
      env:
        HEX_API_KEY: ${{ secrets.HEX_API_KEY }}
